backend:
  name: git-gateway
  branch: master
  commit_messages:
    update: 'Update {{collection}} “{{slug}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "content/index-page.md"
        fields:
          - label: "Page Key"
            name: "pageKey"
            widget: "hidden"
            default: "index-page"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
          - label: "Hero Image"
            name: "heroImage"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Theme Buttons Title"
            name: "themeButtonsTitle"
            widget: "string"
          - label: "Primary Button Text"
            name: "primaryButtonText"
            widget: "string"
          - label: "Secondary Button Text"
            name: "secondaryButtonText"
            widget: "string"
      - label: "Blog Page"
        name: "blogPage"
        file: "content/blog-page.md"
        fields:
          - label: "Page Key"
            name: "pageKey"
            widget: "hidden"
            default: "blog-page"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
          - label: "Post Per Page"
            name: "postPerPage"
            widget: "number"
            default: 5
            min: 1
            max: 10
          - label: "All Blog Post"
            name: "allBlogPost"
            widget: "relation"
            collection: "blogPost"
            default: "list"
            multiple: true
            searchFields: ["title"]
            valueField: "title"
            displayFields: ["title"]
  - name: "blogPost"
    label: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "Blog Title" }
      - { label: "Description", name: "description", widget: "text", default: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "select", options: ["Kim Lian A. Lopez"], default: ["Kim Lian A. Lopez"] }
      - { label: "Cover Image", name: "cover", widget: "image", default: "/img/small-plant-in-table.jpg" }
      - { label: "Cover Image Alt", name: "coverImageAlt", widget: "string", default: "Small plant in table" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string", default: "tech" }
      - { label: "Tags", name: "tags", widget: "list", default: ["tech"] }
      - { label: "Body", name: "body", widget: "markdown", default: "Blog content here..." }

          