backend:
  name: git-gateway
  branch: master
  commit_messages:
    update: 'Update {{collection}} “{{slug}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "content/index-page.md"
        fields:
          - label: "Page Key"
            name: "pageKey"
            widget: "hidden"
            default: "index-page"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
          - label: "Hero Image"
            name: "heroImage"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Theme Buttons Title"
            name: "themeButtonsTitle"
            widget: "string"
          - label: "Primary Button Text"
            name: "primaryButtonText"
            widget: "string"
          - label: "Secondary Button Text"
            name: "secondaryButtonText"
            widget: "string"
  - name: blog
    label: "Post"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "select", options: ["Kim Lian A. Lopez"], default: ["Kim Lian A. Lopez"] }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

          